

USE ContosoRetailDW

SET DATEFORMAT YMD
-- SELECIONANDO DATAS
SELECT DISTINCT
	OS.DateKey
FROM FactOnlineSales OS
WHERE OS.DateKey BETWEEN '2009-01-01' AND '2009-12-31'
/* PARA SELECIONAR DATAS NO FORMATO CORRETO ATRAVÉS DO SET DATEFORMAT YMD, YDM...TRANSFORMA A VISUALIZAÇÃO DAS DATAS
PORÉM, USUALMENTE É RECOMENDADO A UTILIZAÇÃO DAS DATAS COMO ESTÃO ESCRITAS NO BANCO DE DADOS, POIS PODE AFETAR A PERFORMANCE DA ANÁLISE.*/