
USE ContosoRetailDW

-- SELECIONANDO ATUAL
SELECT GETDATE () AS DATA_ATUAL


-- É POSSIVEL ADICIONAR OU SUBTRAIR DATAS
SELECT GETDATE() -10 AS DATA_ATUAL_10


--FILTRANDO
SELECT YEAR(GETDATE()) AS ANO
SELECT MONTH(GETDATE()) AS MES
SELECT DAY(GETDATE()) AS DIA


--FILTRANDO ANOS, MES E DIA DENTRO DO WHERE
SELECT
	*
FROM FactSales
WHERE YEAR(DateKey) = 2009 AND
MONTH(DateKey) = 01 AND
DAY(DateKey) = 15
-- PARA FILTRAR DATAS ESPECÍFICAS. EM CASO DE UM INTERVALO DE DATAS USAR O BETWEEN 